apiVersion: v1
kind: Pod
metadata:
  name: mavenwebapp
  labels:
    app: mavenwebapp
spec:
  containers:
  - name: mavenwebapp
    image: muralidhara9493/maven-web-application:1
    ports:
    - containerPort: 8000
